// <auto-generated />
using System;
using Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Products_Name");

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Products_Price", "[Price] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portátil de 14 pulgadas con procesador Intel i7, 16GB RAM y 512GB SSD.",
                            Name = "Portátil Ultrabook Avanzado",
                            Price = 1250.99m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teléfono móvil con pantalla AMOLED de 6.7 pulgadas y triple cámara.",
                            Name = "Smartphone de Gama Alta",
                            Price = 980.50m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Monitor para gaming y diseño gráfico con resolución UHD y 144Hz.",
                            Name = "Monitor Curvo 32\" 4K",
                            Price = 750.00m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Teclado retroiluminado con switches Cherry MX Blue para una escritura precisa.",
                            Name = "Teclado Mecánico RGB",
                            Price = 155.75m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mouse con diseño vertical para reducir la tensión en la muñeca.",
                            Name = "Mouse Inalámbrico Ergonómico",
                            Price = 89.90m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Auriculares Bluetooth con tecnología de cancelación activa de ruido.",
                            Name = "Auriculares con Cancelación de Ruido",
                            Price = 250.00m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Silla con soporte lumbar ajustable y reposabrazos 4D.",
                            Name = "Silla de Oficina Ergonómica",
                            Price = 320.40m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Prepara espressos y capuccinos con solo pulsar un botón.",
                            Name = "Cafetera Superautomática",
                            Price = 480.00m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Robot que mapea tu hogar y se controla desde una app móvil.",
                            Name = "Robot Aspirador Inteligente",
                            Price = 399.99m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Unidad de almacenamiento portátil USB 3.1 de alta velocidad.",
                            Name = "Disco Duro Externo 2TB",
                            Price = 110.00m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "GPU de última generación para gaming en 1440p y creación de contenido.",
                            Name = "Tarjeta Gráfica RTX 4070",
                            Price = 850.25m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bicicleta con cuadro de aluminio, 21 velocidades y frenos de disco.",
                            Name = "Bicicleta de Montaña R29",
                            Price = 650.00m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Televisor inteligente con tecnología Quantum Dot para colores más vivos.",
                            Name = "Smart TV 55\" QLED",
                            Price = 1150.95m
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Consola de última generación con unidad de estado sólido y gráficos avanzados.",
                            Name = "Consola de Videojuegos Next-Gen",
                            Price = 599.99m
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mochila con compartimentos ocultos y material resistente a cortes.",
                            Name = "Mochila para Portátil Anti-robo",
                            Price = 75.50m
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Herramienta de 18V con dos baterías de litio y maletín de transporte.",
                            Name = "Taladro Percutor Inalámbrico",
                            Price = 130.00m
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Set de 3 sartenes de diferentes tamaños con recubrimiento de titanio.",
                            Name = "Juego de Sartenes Antiadherentes",
                            Price = 95.80m
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lámpara con control táctil, brillo ajustable y temperatura de color variable.",
                            Name = "Lámpara de Escritorio LED",
                            Price = 45.99m
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Freidora sin aceite con capacidad para toda la familia y panel digital.",
                            Name = "Freidora de Aire 5L",
                            Price = 125.00m
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Conjunto de altavoces para una experiencia de cine en casa.",
                            Name = "Sistema de Sonido Envolvente 5.1",
                            Price = 450.60m
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Cámara IP con visión nocturna, detección de movimiento y audio bidireccional.",
                            Name = "Cámara de Seguridad WiFi",
                            Price = 65.00m
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Imprime, escanea y copia con conexión WiFi y alta velocidad de impresión.",
                            Name = "Impresora Multifunción Láser",
                            Price = 210.00m
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Proyector con 8000 lúmenes y capacidad para pantallas de hasta 300 pulgadas.",
                            Name = "Proyector de Vídeo Full HD",
                            Price = 290.50m
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Patinete con autonomía de 30km y velocidad máxima de 25 km/h.",
                            Name = "Patinete Eléctrico Plegable",
                            Price = 420.00m
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Smartwatch con GPS, medidor de frecuencia cardíaca y seguimiento de sueño.",
                            Name = "Reloj Inteligente Deportivo",
                            Price = 199.95m
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elimina el 99.97% de alérgenos y contaminantes del aire en habitaciones medianas.",
                            Name = "Purificador de Aire con Filtro HEPA",
                            Price = 150.00m
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Olla de 6 litros ideal para preparar guisos y carnes tiernas.",
                            Name = "Olla de Cocción Lenta Programable",
                            Price = 85.70m
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Par de mancuernas que permiten cambiar el peso de 2.5kg a 24kg.",
                            Name = "Set de Mancuernas Ajustables",
                            Price = 280.00m
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Esterilla de caucho natural para una práctica de yoga segura y cómoda.",
                            Name = "Esterilla de Yoga Antideslizante",
                            Price = 55.20m
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tienda impermeable y fácil de montar, ideal para excursiones en familia.",
                            Name = "Tienda de Campaña para 4 Personas",
                            Price = 140.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
